#!/usr/bin/env node
/* eslint-disable no-console */
// ─── rebrand.js ───────────────────────────────────────────────────────────────
// One-command white-label rebrand for this Capacitor app.
//
//   Usage:  node scripts/rebrand.js            (uses scripts/rebrand.config.json)
//           node scripts/rebrand.js path/to/other-config.json
//
// SCOPE: web/shared + iOS ONLY. This script does not touch anything under
// android/ — that platform is rebranded by hand (see the note at the bottom of
// this comment for the full list of what that means).
//
// Two separate name fields drive the rename:
//   • appName    → the launcher / home-screen display name. Applied ONLY to
//                  constants.js app_name + iOS CFBundleDisplayName.
//   • STORE_NAME → the brand store name used everywhere else (capacitor
//                  appName, iOS capacitor.config.json appName, and
//                  constants.js STORE_NAME).
//
// What it changes (from the current brand → the config's brand):
//   1. capacitor.config.ts ................ appId, appName(←STORE_NAME)
//   2. src/config/constants.js ............ appid, STORE_NAME(←STORE_NAME),
//      app_name(←appName)
//      (+ STORE_ID / BRANCH / THEME_ID / appleid only if set in the config)
//   3. ios/App/App/capacitor.config.json .. appId, appName(←STORE_NAME)
//      (also auto-regenerated later by `npx cap sync ios`)
//   4. ios/App/App/Info.plist ............. CFBundleDisplayName(←appName),
//      the two CFBundleURLName entries (razorpay + myapp)
//   5. ios/App/App/AppDelegate.swift ...... the hardcoded "<appId>.myapp"
//      URL-scheme comparison
//
// versionCode / versionName are still REQUIRED in the config, but nothing is
// written from them any more — they only feed the iOS checklist below, which
// tells you which MARKETING_VERSION / CURRENT_PROJECT_VERSION to set in Xcode.
//
// What it deliberately does NOT change on Android — all by hand:
//   • android/app/build.gradle .......... namespace, applicationId,
//                                        versionCode, versionName, keystore
//   • android/.../res/values/strings.xml  app_name, title_activity_main,
//                                        package_name, custom_url_scheme
//   • android/.../AndroidManifest.xml ... package="" (absent under AGP 8)
//   • android/.../assets/capacitor.config.json (regenerated by `npx cap sync`)
//   • android/.../java/<pkg>/MainActivity.java — the `package …;` line AND the
//     folder path itself must both be moved to match the new applicationId
//   • android/app/google-services.json — re-download from the brand's Firebase
//     project, or the build fails with "No matching client found"
//
// What it deliberately does NOT change on iOS:
//   • ios/App/App.xcodeproj/project.pbxproj — PRODUCT_BUNDLE_IDENTIFIER,
//     INFOPLIST_KEY_CFBundleDisplayName, MARKETING_VERSION and
//     CURRENT_PROJECT_VERSION live here and are the REAL shipped identity.
//     Change them in Xcode; the script only reads the file to warn you when it
//     still holds the old bundle id. See the post-run checklist.
//   • The "myapp" URL scheme itself — it is hardcoded as PhonePe's appSchema in
//     several src/components files, so it is payment plumbing, not branding.
//   • GoogleService-Info.plist — must be re-downloaded from the brand's
//     Firebase project. The script only verifies BUNDLE_ID and warns.
//
// Safety: all files are read + verified FIRST; nothing is written unless every
// expected pattern is found. Exits non-zero with a clear message otherwise.
// Patterns marked `optional` never abort the run; they are collected and
// reported as warnings so a silent skip can't look like a success.
//
// Note: the iOS bundle id is detected from project.pbxproj rather than assumed
// to equal capacitor.config.ts's appId. The two drift whenever a past rebrand
// only touched the web side — this repo has been observed carrying three
// different ids at once across capacitor.config.ts, pbxproj and constants.js.

const fs = require("fs");
const path = require("path");

const ROOT = path.resolve(__dirname, "..");
const rel = (p) => path.relative(ROOT, p).replace(/\\/g, "/");

// ── 1. Load config ────────────────────────────────────────────────────────────
// Flags are filtered out so the config path stays the first positional arg.
const argv = process.argv.slice(2);
const DRY_RUN = argv.includes("--dry-run") || argv.includes("-n");
const configPath = path.resolve(
  ROOT,
  argv.find((a) => !a.startsWith("-")) || "scripts/rebrand.config.json",
);
if (!fs.existsSync(configPath)) {
  console.error(`✖ Config not found: ${configPath}`);
  process.exit(1);
}
const cfg = JSON.parse(fs.readFileSync(configPath, "utf8"));

for (const key of ["appId", "appName", "STORE_NAME", "versionCode", "versionName"]) {
  if (cfg[key] === undefined || cfg[key] === "") {
    console.error(`✖ Config is missing required field "${key}"`);
    process.exit(1);
  }
}
if (!/^[a-z][a-z0-9_]*(\.[a-z][a-z0-9_]*)+$/i.test(cfg.appId)) {
  console.error(`✖ "${cfg.appId}" is not a valid reverse-DNS application id`);
  process.exit(1);
}
// The Apple App ID is the numeric App Store id (e.g. 6760403859), NOT the
// bundle id. Getting these two confused silently breaks the iOS force-update
// and "rate us" links, which fail at runtime rather than at build time.
if (cfg.appleid !== undefined && !/^\d{6,}$/.test(String(cfg.appleid))) {
  console.error(
    `✖ "${cfg.appleid}" is not a valid Apple App ID — expected the numeric\n` +
      `  App Store id (e.g. "6760403859"), not the bundle identifier.`,
  );
  process.exit(1);
}

// ── 2. Detect the CURRENT brand from capacitor.config.ts ────────────────────
const capConfigPath = path.join(ROOT, "capacitor.config.ts");
const capConfigSrc = fs.readFileSync(capConfigPath, "utf8");
const oldId = capConfigSrc.match(/appId:\s*["']([^"']+)["']/)?.[1];
const oldName = capConfigSrc.match(/appName:\s*["']([^"']+)["']/)?.[1];
if (!oldId || !oldName) {
  console.error("✖ Could not detect current appId/appName in capacitor.config.ts");
  process.exit(1);
}

// ── 2c. Detect the CURRENT iOS bundle id from project.pbxproj (READ-ONLY) ───
// Not rewritten by this script — the pbxproj is edited in Xcode. Read purely so
// the post-run checklist can tell you whether the shipped identity is stale.
// The value is unquoted in the pbxproj: `PRODUCT_BUNDLE_IDENTIFIER = com.x.y;`
const pbxprojFile = "ios/App/App.xcodeproj/project.pbxproj";
let oldIosId = null;
const pbxprojPath = path.join(ROOT, pbxprojFile);
if (fs.existsSync(pbxprojPath)) {
  oldIosId =
    fs
      .readFileSync(pbxprojPath, "utf8")
      .match(/PRODUCT_BUNDLE_IDENTIFIER\s*=\s*"?([A-Za-z0-9_.-]+)"?\s*;/)?.[1] ?? null;
}

const newId = cfg.appId;
const newName = cfg.appName;       // launcher / activity app name  → app_name only
const newStoreName = cfg.STORE_NAME; // brand store name → capacitor appName + STORE_NAME
console.log(`\nRebrand: ${oldId}  →  ${newId}`);
console.log(`  launcher app_name → "${newName}"  (was "${oldName}" in capacitor.config.ts)`);
console.log(`  store name        → "${newStoreName}"`);
if (cfg.appleid !== undefined) console.log(`  apple app id      → ${cfg.appleid}`);
if (oldIosId !== null && oldIosId !== newId) {
  console.log(
    `\n⚠ iOS bundle id is ${oldIosId} in project.pbxproj. That file is NOT\n` +
      `  rewritten by this script — you must change it in Xcode, otherwise the\n` +
      `  iOS build still ships the old brand. Details in the checklist below.`,
  );
}
console.log("");

// ── 3. Prepare all edits in memory (verify every pattern before writing) ────
const edits = []; // { file, content }
const problems = [];
const warnings = [];

// `optionalFile: true` — the whole file may be absent (e.g. the iOS platform was
// never added). Missing then means "nothing to do", not a failure.
function planEdit(file, transforms, { optionalFile = false } = {}) {
  const full = path.join(ROOT, file);
  if (!fs.existsSync(full)) {
    if (!optionalFile) problems.push(`${file}: file not found`);
    return;
  }
  const original = fs.readFileSync(full, "utf8");
  let content = original;
  for (const t of transforms) {
    if (!t.pattern.test(content)) {
      // Optional patterns must still be surfaced. A silently skipped transform
      // reads as "rebranded ✔" while the old brand is still in the build.
      if (t.optional) {
        warnings.push(`${file}: skipped (pattern not present) → ${t.describe}`);
        continue;
      }
      problems.push(`${file}: expected pattern not found → ${t.describe}`);
      continue;
    }
    content = content.replace(t.pattern, t.replacement);
  }
  // Every transform is idempotent, so an unchanged file simply needs no write.
  if (content !== original) edits.push({ file: full, content });
}

// 3.1 capacitor.config.ts
planEdit("capacitor.config.ts", [
  {
    pattern: /appId:\s*["'][^"']+["']/,
    replacement: `appId: "${newId}"`,
    describe: "appId",
  },
  {
    pattern: /appName:\s*["'][^"']+["']/,
    replacement: `appName: "${newStoreName}"`,
    describe: "appName",
  },
]);

// 3.2 src/config/constants.js — appid, STORE_NAME, app_name (+ optional keys)
const constantsTransforms = [
  {
    pattern: /appid:\s*["'][^"']*["']/,
    replacement: `appid: "${newId}"`,
    describe: "appid",
  },
  {
    pattern: /STORE_NAME:\s*["'][^"']*["']/,
    replacement: `STORE_NAME: "${newStoreName}"`,
    describe: "STORE_NAME",
  },
  {
    pattern: /app_name:\s*["'][^"']*["']/,
    replacement: `app_name: "${newName}"`,
    describe: "app_name",
  },
];
if (cfg.STORE_ID !== undefined)
  constantsTransforms.push({
    pattern: /STORE_ID:\s*\d+/,
    replacement: `STORE_ID: ${cfg.STORE_ID}`,
    describe: "STORE_ID",
  });
if (cfg.THEME_ID !== undefined)
  constantsTransforms.push({
    pattern: /THEME_ID:\s*\d+/,
    replacement: `THEME_ID: ${cfg.THEME_ID}`,
    describe: "THEME_ID",
  });
if (cfg.BRANCH !== undefined) {
  constantsTransforms.push({
    // \b so this does NOT match the "BRANCH:" inside "DEFAULT_BRANCH:"
    pattern: /\bBRANCH:\s*["'][^"']*["']/,
    replacement: `BRANCH: "${cfg.BRANCH}"`,
    describe: "BRANCH",
  });
  constantsTransforms.push({
    pattern: /DEFAULT_BRANCH:\s*["'][^"']*["']/,
    replacement: `DEFAULT_BRANCH: "${cfg.BRANCH}"`,
    describe: "DEFAULT_BRANCH",
  });
}
if (cfg.appleid !== undefined)
  constantsTransforms.push({
    pattern: /appleid:\s*["'][^"']*["']/,
    replacement: `appleid: "${cfg.appleid}"`,
    describe: "appleid",
  });
planEdit("src/config/constants.js", constantsTransforms);

// ── 3.3 iOS ─────────────────────────────────────────────────────────────────
// Every iOS file is optional: a checkout without the ios/ platform must still
// rebrand the web/shared files cleanly.

// Matches `<key>NAME</key><string>value</string>` across the newline+tab layout
// Xcode writes. Captures the prefix and suffix so only the value is rewritten.
const plistValue = (key) =>
  new RegExp(`(<key>${key}</key>\\s*<string>)[^<]*(</string>)`);

// A CFBundleURLTypes entry is identified by the SCHEME it declares, not by its
// current CFBundleURLName — the name is exactly the stale value we're replacing,
// so it cannot be used as the anchor. CFBundleURLName always precedes
// CFBundleURLSchemes within a dict, so anchor forward onto the scheme.
const urlNameForScheme = (scheme) =>
  new RegExp(
    `(<key>CFBundleURLName</key>\\s*<string>)[^<]*` +
      `(</string>\\s*<key>CFBundleURLSchemes</key>\\s*<array>\\s*<string>${scheme}</string>)`,
  );

// 3.3a ios/App/App/capacitor.config.json — regenerated by `npx cap sync ios`,
// kept correct on disk so a build without a sync still carries the right
// identity.
planEdit(
  "ios/App/App/capacitor.config.json",
  [
    {
      pattern: /"appId":\s*"[^"]*"/,
      replacement: `"appId": "${newId}"`,
      describe: "appId",
    },
    {
      pattern: /"appName":\s*"[^"]*"/,
      replacement: `"appName": "${newStoreName}"`,
      describe: "appName",
    },
  ],
  { optionalFile: true },
);

// 3.3b ios/App/App/Info.plist
// CFBundleDisplayName is the iOS home-screen label, so it takes appName, the
// launcher-name field — not STORE_NAME.
// NOTE: this project has GENERATE_INFOPLIST_FILE off, so the value in THIS file
// is what ships; pbxproj's INFOPLIST_KEY_CFBundleDisplayName is inert but
// should be kept in sync by hand to avoid a confusing mismatch.
planEdit(
  "ios/App/App/Info.plist",
  [
    {
      pattern: plistValue("CFBundleDisplayName"),
      replacement: `$1${newName}$2`,
      describe: "CFBundleDisplayName",
    },
    {
      pattern: urlNameForScheme("razorpay"),
      replacement: `$1${newId}.razorpay$2`,
      describe: "CFBundleURLName for the razorpay scheme",
      optional: true,
    },
    {
      pattern: urlNameForScheme("myapp"),
      replacement: `$1${newId}$2`,
      describe: "CFBundleURLName for the myapp scheme",
      optional: true,
    },
  ],
  { optionalFile: true },
);

// 3.3c ios/App/App/AppDelegate.swift — the deep-link handler compares against a
// hardcoded "<bundle id>.myapp". Value-agnostic: `[\w.]+` backtracks so the
// literal ".myapp" suffix is preserved rather than swallowed, which also makes
// the transform idempotent across re-runs.
planEdit(
  "ios/App/App/AppDelegate.swift",
  [
    {
      pattern: /(url\.scheme\s*==\s*")[\w.]+(\.myapp")/,
      replacement: `$1${newId}$2`,
      describe: "hardcoded <appId>.myapp URL scheme comparison",
      optional: true,
    },
  ],
  { optionalFile: true },
);

// ── 4. Abort if anything didn't match ────────────────────────────────────────
if (problems.length) {
  console.error("✖ Aborted — no files were changed. Problems:\n");
  problems.forEach((p) => console.error("  • " + p));
  process.exit(1);
}

// Decided after planning, so it reflects every file the script touches — not
// just capacitor.config.ts. Any drift anywhere still gets fixed.
// Printed before the writes so it is visible even when the edit list is long.
if (warnings.length) {
  console.log("⚠ Skipped (not fatal — verify each one is genuinely absent):\n");
  warnings.forEach((w) => console.log("  • " + w));
  console.log("");
}

if (!edits.length) {
  console.log("Nothing to do — every file already matches the config.");
  process.exit(0);
}

// ── 5. Write everything ──────────────────────────────────────────────────────
for (const e of edits) {
  if (!DRY_RUN) fs.writeFileSync(e.file, e.content, "utf8");
  console.log(`${DRY_RUN ? "· would update" : "✔ updated "} ${rel(e.file)}`);
}

// ── 6. Post-run checklist (things a script cannot do for you) ────────────────
if (DRY_RUN) {
  console.log(
    `\n🔍 DRY RUN — nothing was written. Re-run without --dry-run to apply.\n` +
      `   Target: ${newId} ("${newName}") v${cfg.versionName} (code ${cfg.versionCode})\n`,
  );
} else {
  console.log(
    `\n✅ Rebranded to ${newId} ("${newName}") v${cfg.versionName} (code ${cfg.versionCode})\n`,
  );
}
// Auto-numbered so adding or skipping a step never leaves a gap in the list.
let stepNo = 0;
const step = (text) => {
  const n = `  ${++stepNo}. `;
  console.log(n + text.split("\n").join("\n" + " ".repeat(n.length)));
};

console.log("── REQUIRED next steps ─────────────────────────────────────────");

// ── iOS — only worth printing when the platform is actually present ──────────
if (fs.existsSync(path.join(ROOT, "ios/App/App"))) {
  console.log("\n IOS");

  // The pbxproj is the real shipped identity and this script never writes it.
  if (oldIosId === null) {
    step(
      `⚠ Could not read PRODUCT_BUNDLE_IDENTIFIER from ${pbxprojFile}.\n` +
        `Open the project in Xcode and confirm the bundle id is ${newId}.`,
    );
  } else if (oldIosId === newId) {
    step(`project.pbxproj bundle id is already ${newId} ✔`);
  } else {
    step(
      `⚠ EDIT ${pbxprojFile} IN XCODE — it still ships ${oldIosId}.\n` +
        `This script does not touch the pbxproj. In Xcode → target "App" →\n` +
        `Build Settings, set for BOTH Debug and Release:\n` +
        `  • PRODUCT_BUNDLE_IDENTIFIER        = ${newId}\n` +
        `  • INFOPLIST_KEY_CFBundleDisplayName = ${newName}\n` +
        `  • MARKETING_VERSION                = ${cfg.versionName}\n` +
        `  • CURRENT_PROJECT_VERSION          = ${cfg.versionCode}\n` +
        `Until this is done the iOS build carries the OLD brand, regardless\n` +
        `of everything the script just rewrote.`,
    );
  }

  // Distinct file from android/app/google-services.json — that one is not
  // checked here (Android is out of scope) but must be replaced too.
  const gsIosPath = path.join(ROOT, "ios/App/App/GoogleService-Info.plist");
  if (fs.existsSync(gsIosPath)) {
    const iosBundle = fs
      .readFileSync(gsIosPath, "utf8")
      .match(/<key>BUNDLE_ID<\/key>\s*<string>([^<]*)<\/string>/)?.[1];
    if (iosBundle === newId) {
      step("GoogleService-Info.plist already matches the new bundle id ✔");
    } else {
      step(
        `⚠ REPLACE ios/App/App/GoogleService-Info.plist — its BUNDLE_ID is\n` +
          `${iosBundle ?? "(unreadable)"}, not ${newId}. Add an iOS app with this\n` +
          `bundle id in the brand's Firebase project and download the new\n` +
          `plist. This is a SEPARATE file from google-services.json; push\n` +
          `notifications fail silently at runtime if it is wrong.`,
      );
    }
  }

  step(
    `⚠ Apple App Store id: ${
      cfg.appleid !== undefined
        ? `set to ${cfg.appleid} in src/config/constants.js.\nVerify it is this brand's app in App Store Connect.`
        : `NOT set — "appleid" is inactive in the config, so constants.js\nstill holds the previous brand's id. The iOS force-update and\n"rate us" links will point at the wrong app.`
    }`,
  );

  step(
    "⚠ Signing: create the App ID for this bundle id in the Apple Developer\n" +
      "portal with Push Notifications enabled, then a matching provisioning\n" +
      "profile. Also set ios/App/App/App.entitlements aps-environment to\n" +
      "\"production\" for TestFlight/App Store builds (it is \"development\"\n" +
      "in a fresh checkout, which silently breaks push on release).",
  );

  step(
    "App icon: ios/App/App/Assets.xcassets still holds the previous brand's\n" +
      "icon. Regenerate with:  npx capacitor-assets generate --ios",
  );
}

console.log("\n WEB / SHARED");
step(
  "Rebuild:\n" +
    "  npm run build\n" +
    "  npx cap sync ios && (cd ios/App && pod install)\n" +
    "  → open ios/App/App.xcworkspace in Xcode",
);
step(
  "If the brand uses a different backend store, activate STORE_ID /\n" +
    "BRANCH in scripts/rebrand.config.json (remove the underscore) and\n" +
    "re-run — or edit src/config/constants.js manually.",
);
step(
  "⚠ ANDROID IS OUT OF SCOPE for this script — rebrand it by hand:\n" +
    `  • android/app/build.gradle .......... namespace + applicationId → ${newId}\n` +
    `                                       versionCode ${cfg.versionCode}, versionName ${cfg.versionName}\n` +
    `  • .../res/values/strings.xml ........ app_name + title_activity_main → ${newName}\n` +
    `                                       package_name + custom_url_scheme → ${newId}\n` +
    "  • .../AndroidManifest.xml ........... package=\"\" (absent under AGP 8)\n" +
    `  • .../assets/capacitor.config.json .. appId → ${newId}, appName → ${newStoreName}\n` +
    "                                       (or just run `npx cap sync android`)\n" +
    `  • .../java/<pkg>/MainActivity.java .. move the folder to ${newId
      .split(".")
      .join("/")}/\n` +
    `                                       and set \`package ${newId};\`\n` +
    "  • android/app/google-services.json .. re-download from the brand's\n" +
    "                                       Firebase project, else the build\n" +
    "                                       fails: No matching client found\n" +
    "  • signingConfigs.release keystore ... each brand needs its own",
);
console.log("\n────────────────────────────────────────────────────────────────\n");
